"""TrustChain notarization enforcement — block unproven file changes."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Set

from apatch.enforcement_messages import (
    POLICY_SUMMARY,
    apply_blocked_message,
    build_rejection_prompt,
    wrap_rejection_result,
)
from apatch.git_util import find_git_root
from apatch.trustchain_helper import TrustChainHelper


def _git_available() -> bool:
    return shutil.which("git") is not None

ENFORCEMENT_REL = os.path.join(".apatch", "enforcement.json")
NOTARIZED_INDEX_REL = os.path.join(".apatch", "notarized_index.json")

GOVERNED_MODE_OFF = "off"
GOVERNED_MODE_AUTO_SESSION = "auto_session"
GOVERNED_MODE_STRICT = "strict"
VALID_GOVERNED_MODES = frozenset({
    GOVERNED_MODE_OFF,
    GOVERNED_MODE_AUTO_SESSION,
    GOVERNED_MODE_STRICT,
})

DEFAULT_ENFORCEMENT: Dict[str, Any] = {
    "mode": "strict",
    "governed_mode": GOVERNED_MODE_OFF,
    "policy": POLICY_SUMMARY,
    "block_commit_without_proof": True,
    "require_trustchain_on_apply": True,
    "fail_apply_if_notarization_fails": True,
    "incremental_notarization": True,
    "require_ed25519_block_on_disk": True,
}

SKIP_PATH_PREFIXES = (
    ".apatch/",
    ".trustchain/",
    ".git/",
    "node_modules/",
    "__pycache__/",
    ".venv/",
    "venv/",
)

# Machine-local IDE transport configuration is generated by `apatch mcp sync`
# and is not product source. Cursor rules and other project policy remain tracked.
SKIP_EXACT_PATHS = frozenset({".cursor/mcp.json"})

_APATCH_POLICY_REGISTERED = False


def enforcement_config_path(root: str) -> str:
    return os.path.join(os.path.abspath(root), ENFORCEMENT_REL)


def notarized_index_path(root: str) -> str:
    return os.path.join(os.path.abspath(root), NOTARIZED_INDEX_REL)


def is_enforcement_enabled(root: str = ".") -> bool:
    if os.environ.get("APATCH_ENFORCE", "").strip().lower() in ("1", "true", "yes"):
        return True
    path = enforcement_config_path(root)
    if os.path.isfile(path):
        try:
            with open(path, encoding="utf-8") as handle:
                data = json.load(handle)
            return data.get("mode", "strict") != "off"
        except (OSError, json.JSONDecodeError):
            return True
    return False


def load_enforcement_config(root: str = ".") -> Dict[str, Any]:
    cfg = dict(DEFAULT_ENFORCEMENT)
    path = enforcement_config_path(root)
    if os.path.isfile(path):
        try:
            with open(path, encoding="utf-8") as handle:
                data = json.load(handle)
            if isinstance(data, dict):
                cfg.update(data)
        except (OSError, json.JSONDecodeError):
            pass
    gm = cfg.get("governed_mode", GOVERNED_MODE_OFF)
    if gm not in VALID_GOVERNED_MODES:
        cfg["governed_mode"] = GOVERNED_MODE_OFF
    return cfg


# Strictness ordering for governed_mode. Higher = more constrained.
_GOVERNED_MODE_RANK = {
    GOVERNED_MODE_OFF: 0,
    GOVERNED_MODE_AUTO_SESSION: 1,
    GOVERNED_MODE_STRICT: 2,
}


def resolve_governed_mode(root: str = ".") -> str:
    """Resolve effective governed_mode (reference-monitor: env may only ratchet up).

    The committed ``enforcement.json`` is the floor. ``APATCH_GOVERNED_MODE`` can
    only make governance *stricter* than the committed config — it can never
    weaken it. This closes the env-kill-switch bypass (RFP-005 §audit #2): the
    monitored party cannot disable governance by exporting ``=off``.

    Note (RFP-005 §audit #8): ``governed_mode`` only selects *how* a session is
    obtained (auto vs explicit). The *requirement* for a governed session under
    enforcement is enforced independently by the state machine
    (``_session_block_message`` keys off ``is_enforcement_enabled``), so a bare
    ``{"mode": "strict"}`` config still gates mutations even when governed_mode
    is ``off``. Safe scaffolding defaults live in ``init_consumer`` / CLI.
    """
    cfg = load_enforcement_config(root)
    file_mode = cfg.get("governed_mode", GOVERNED_MODE_OFF)
    if file_mode not in VALID_GOVERNED_MODES:
        file_mode = GOVERNED_MODE_OFF

    env = os.environ.get("APATCH_GOVERNED_MODE", "").strip().lower()
    if env in VALID_GOVERNED_MODES:
        if _GOVERNED_MODE_RANK[env] >= _GOVERNED_MODE_RANK[file_mode]:
            return env
        # Env tried to weaken a committed floor → ignore the downgrade.
        return file_mode
    return file_mode


def write_enforcement_config(
    root: str,
    *,
    mode: str = "strict",
    governed_mode: str = GOVERNED_MODE_AUTO_SESSION,
) -> str:
    path = enforcement_config_path(root)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    cfg = dict(DEFAULT_ENFORCEMENT)
    cfg["mode"] = mode
    if governed_mode in VALID_GOVERNED_MODES:
        cfg["governed_mode"] = governed_mode
    cfg["enabled_at"] = datetime.now(timezone.utc).isoformat()
    with open(path, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2, ensure_ascii=False)
        f.write("\n")
    return path


def _normalize_rel(rel_path: str) -> str:
    """Normalize separators and strip './' prefixes, preserving leading dots.

    lstrip('./') strips dot *characters*, so control-plane paths like
    '.github/workflows/ci.yml' became 'github/workflows/ci.yml' — the notarized
    index keyed them without the dot and the on-disk existence check then looked
    up a non-existent path, reporting the file as deleted. Canonical
    implementation lives in apatch.apatch_paths.normalize_rel.
    """
    from apatch.apatch_paths import normalize_rel

    return normalize_rel(rel_path)


def _should_track(rel_path: str) -> bool:
    norm = _normalize_rel(rel_path)
    if not norm or norm.endswith(".pyc"):
        return False
    if norm in SKIP_EXACT_PATHS:
        return False
    return not any(norm.startswith(p) for p in SKIP_PATH_PREFIXES)


def file_sha256(abs_path: str) -> str:
    import hashlib

    h = hashlib.sha256()
    with open(abs_path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _empty_index() -> Dict[str, Any]:
    return {
        "version": 3,
        "updated_at": None,
        "files": {},
        "committed_files": {},
        "ledger": {"entries": None, "head": None},
    }


def load_notarized_index(root: str) -> Dict[str, Any]:
    path = notarized_index_path(root)
    if not os.path.isfile(path):
        return _empty_index()
    try:
        with open(path, encoding="utf-8") as handle:
            data = json.load(handle)
        if isinstance(data, dict) and isinstance(data.get("files"), dict):
            if not isinstance(data.get("committed_files"), dict):
                data["committed_files"] = {}
                if int(data.get("version") or 0) >= 3:
                    data["committed_files"] = {
                        rel: dict(entry)
                        for rel, entry in data["files"].items()
                        if isinstance(entry, dict) and entry.get("attested")
                    }
            return data
    except (OSError, json.JSONDecodeError):
        pass
    return _empty_index()


def save_notarized_index(root: str, index: Dict[str, Any]) -> None:
    from apatch.runtime.atomic_io import atomic_write_json

    path = notarized_index_path(root)
    index["updated_at"] = datetime.now(timezone.utc).isoformat()
    atomic_write_json(path, index)


def _ledger_entry_order(row: Dict[str, Any]) -> tuple[float, int, str]:
    """Chronological order independent of lexicographic ledger filenames."""
    raw_timestamp = row.get("timestamp")
    timestamp = float("-inf")
    if isinstance(raw_timestamp, (int, float)):
        timestamp = float(raw_timestamp)
    elif isinstance(raw_timestamp, str) and raw_timestamp.strip():
        try:
            timestamp = float(raw_timestamp)
        except ValueError:
            try:
                timestamp = datetime.fromisoformat(
                    raw_timestamp.replace("Z", "+00:00")
                ).timestamp()
            except ValueError:
                pass

    raw_id = str(row.get("id") or "")
    id_tail = raw_id.rsplit("_", 1)[-1]
    sequence = int(id_tail) if id_tail.isdigit() else -1
    return timestamp, sequence, str(row.get("object_path") or "")


def _ledger_session_id(row: Dict[str, Any]) -> Optional[str]:
    payload = row.get("payload") or {}
    raw = payload.get("governed_session_id") or payload.get("session_id")
    value = str(raw or "").strip()
    return value or None


def _is_attestation_row(row: Dict[str, Any]) -> bool:
    if not row.get("signature"):
        return False
    payload = row.get("payload") or {}
    tool_id = str(row.get("tool_id") or "")
    return tool_id == "apatch_attest" or (
        tool_id in ("apatch", "apatch_expert") and payload.get("action") == "attest"
    )


def rebuild_notarized_index_from_ledger(root: str) -> Dict[str, Any]:
    """Rebuild the committed-state notarization index from signed ledger objects."""
    tc = TrustChainHelper(root, auto_init=False)
    index = _empty_index()
    if not tc.has_trustchain():
        return index

    rows = list(tc.iter_ledger_entries())
    ordered = sorted(rows, key=_ledger_entry_order)
    attestations: Dict[str, List[tuple[tuple[float, int, str], Dict[str, Any]]]] = {}
    for row in ordered:
        session_id = _ledger_session_id(row)
        if session_id and _is_attestation_row(row):
            attestations.setdefault(session_id, []).append((_ledger_entry_order(row), row))

    latest_order: Dict[str, tuple[float, int, str]] = {}
    latest_committed_order: Dict[str, tuple[float, int, str]] = {}
    for row in ordered:
        row_order = _ledger_entry_order(row)
        if row.get("tool_id") not in (None, "apatch", "apatch_expert"):
            continue
        payload = row.get("payload") or {}
        files = payload.get("files") or {}
        if not isinstance(files, dict):
            continue
        session_id = _ledger_session_id(row)
        subsequent = [
            item for item in attestations.get(session_id or "", []) if item[0] > row_order
        ]
        attestation_row = min(subsequent, key=lambda item: item[0])[1] if subsequent else None
        for rel_path, meta in files.items():
            if not isinstance(meta, dict):
                continue
            sha = meta.get("sha256")
            if not sha:
                continue
            norm = _normalize_rel(rel_path)
            if not _should_track(norm):
                continue
            previous_order = latest_order.get(norm)
            if previous_order is not None and row_order <= previous_order:
                continue
            latest_order[norm] = row_order
            entry = {
                "sha256": sha,
                "signature": row.get("signature"),
                "object_path": row.get("object_path"),
                "committed_at": row.get("timestamp"),
                "governed_session_id": session_id,
                "attested": attestation_row is not None,
                "attestation_signature": (
                    attestation_row.get("signature") if attestation_row else None
                ),
                "attestation_object_path": (
                    attestation_row.get("object_path") if attestation_row else None
                ),
            }
            index["files"][norm] = entry
            previous_committed = latest_committed_order.get(norm)
            if attestation_row is not None and (
                previous_committed is None or row_order > previous_committed
            ):
                latest_committed_order[norm] = row_order
                index["committed_files"][norm] = dict(entry)
    index["ledger"] = {
        "entries": len(rows),
        "head": tc.ledger_head(),
    }
    save_notarized_index(root, index)
    return index


def record_notarized_files(
    root: str,
    files_meta: Dict[str, Dict[str, Any]],
    *,
    signature: Optional[str] = None,
    object_path: Optional[str] = None,
    ledger_length: Optional[int] = None,
    ledger_head: Optional[str] = None,
    governed_session_id: Optional[str] = None,
) -> None:
    """Record a signed mutation; it becomes committed only after session attestation."""
    if not files_meta:
        return
    from apatch.runtime.atomic_io import exclusive_file_lock

    path = notarized_index_path(root)
    with exclusive_file_lock(path):
        index = load_notarized_index(root)
        index["version"] = 3
        index.setdefault("committed_files", {})
        now = datetime.now(timezone.utc).isoformat()
        session_id = str(governed_session_id or "").strip() or None
        for rel_path, meta in files_meta.items():
            norm = _normalize_rel(rel_path)
            if not _should_track(norm):
                continue
            sha = meta.get("sha256") if isinstance(meta, dict) else None
            if not sha:
                continue
            index["files"][norm] = {
                "sha256": sha,
                "signature": signature,
                "object_path": object_path,
                "committed_at": now,
                "governed_session_id": session_id,
                "attested": False,
                "attestation_signature": None,
                "attestation_object_path": None,
            }
        if ledger_length is not None or ledger_head is not None:
            index["ledger"] = {"entries": ledger_length, "head": ledger_head}
        save_notarized_index(root, index)


def record_session_attested(
    root: str,
    session_id: str,
    *,
    signature: Optional[str] = None,
    object_path: Optional[str] = None,
) -> int:
    """Atomically promote exact mutation hashes from one verified session to committed."""
    normalized_session = str(session_id or "").strip()
    if not normalized_session:
        return 0
    from apatch.runtime.atomic_io import exclusive_file_lock

    path = notarized_index_path(root)
    with exclusive_file_lock(path):
        index = load_notarized_index(root)
        index["version"] = 3
        committed_files = index.setdefault("committed_files", {})
        updated = 0
        for rel, entry in (index.get("files") or {}).items():
            if not isinstance(entry, dict):
                continue
            if entry.get("governed_session_id") != normalized_session:
                continue
            entry["attested"] = True
            entry["attestation_signature"] = signature
            entry["attestation_object_path"] = object_path
            committed_files[rel] = dict(entry)
            updated += 1
        if updated:
            save_notarized_index(root, index)
        return updated


def _git_staged_files(root: str) -> List[str]:
    if not _git_available():
        return []
    gr = find_git_root(root) or root
    proc = subprocess.run(
        ["git", "-C", gr, "diff", "--cached", "--name-only", "--diff-filter=ACMR"],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        return []
    return [ln.strip() for ln in proc.stdout.splitlines() if ln.strip()]


def _git_unstaged_modified(root: str) -> List[str]:
    if not _git_available():
        return []
    gr = find_git_root(root) or root
    proc = subprocess.run(
        ["git", "-C", gr, "diff", "--name-only", "--diff-filter=ACMR"],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        return []
    return [ln.strip() for ln in proc.stdout.splitlines() if ln.strip()]


def verify_paths_notarized(
    root: str,
    paths: List[str],
    *,
    rebuild_index: bool = False,
) -> Dict[str, Any]:
    """Check that on-disk content matches last notarized sha256 for each path."""
    root = os.path.abspath(root)
    did_rebuild = bool(rebuild_index)
    index = rebuild_notarized_index_from_ledger(root) if rebuild_index else load_notarized_index(root)
    if rebuild_index is False and not index.get("files"):
        index = rebuild_notarized_index_from_ledger(root)
        did_rebuild = True

    notarized: Dict[str, Any] = index.get("files") or {}
    violations: List[Dict[str, Any]] = []
    checked_paths: List[str] = []
    ignored_paths: List[str] = []

    for rel in paths:
        norm = _normalize_rel(rel)
        if not _should_track(norm):
            if norm not in ignored_paths:
                ignored_paths.append(norm)
            continue
        checked_paths.append(norm)
        abs_path = os.path.join(root, norm)
        if not os.path.isfile(abs_path):
            if norm in notarized:
                violations.append({
                    "path": norm,
                    "reason": "file_deleted_without_notarized_delete",
                })
            continue
        actual = file_sha256(abs_path)
        entry = notarized.get(norm)
        if not entry:
            violations.append({
                "path": norm,
                "reason": "never_notarized",
                "actual_sha256": actual,
                "hint": "Нет Ed25519 block в .trustchain/chain/ или objects/ для этого файла.",
            })
            continue
        expected = entry.get("sha256")
        if expected != actual:
            violations.append({
                "path": norm,
                "reason": "sha256_mismatch",
                "expected_sha256": expected,
                "actual_sha256": actual,
                "hint": "Правка вне apatch (sed/re/search_replace) — подпись не покрывает текущее содержимое.",
            })

    tc = TrustChainHelper(root, auto_init=False)
    ledger_meta = index.get("ledger") or {}
    result: Dict[str, Any] = {
        "ok": len(violations) == 0,
        "enforcement": is_enforcement_enabled(root),
        "checked": len(checked_paths),
        "ignored": len(ignored_paths),
        "ignored_paths": ignored_paths[:10],
        "violations": violations,
        "notarized_file_count": len(notarized),
        "signed_blocks_on_disk": ledger_meta.get("entries"),
        "ledger_entries": ledger_meta.get("entries"),
        "ledger_head": tc.ledger_head() or ledger_meta.get("head"),
        "ledger_scan": "full_rebuild" if did_rebuild else "cached",
        "policy": POLICY_SUMMARY,
    }
    if violations:
        primary = violations[0].get("reason", "never_notarized")
        return wrap_rejection_result(result, reason=str(primary))
    return result


def verify_notarization_workspace(
    target_dir: str = ".",
    *,
    staged: bool = False,
    working_tree: bool = False,
    rebuild_index: bool = False,
) -> Dict[str, Any]:
    root = os.path.abspath(target_dir)
    paths: Set[str] = set()
    if staged:
        paths.update(_git_staged_files(root))
    if working_tree:
        paths.update(_git_unstaged_modified(root))
    if not paths:
        tc = TrustChainHelper(root, auto_init=False)
        index = rebuild_notarized_index_from_ledger(root) if rebuild_index else load_notarized_index(root)
        ledger_meta = index.get("ledger") or {}
        return {
            "ok": True,
            "enforcement": is_enforcement_enabled(root),
            "checked": 0,
            "violations": [],
            "ledger_entries": ledger_meta.get("entries"),
            "ledger_head": tc.ledger_head() or ledger_meta.get("head"),
            "ledger_scan": "full_rebuild" if rebuild_index else "cached",
            "message": "no paths to check",
        }
    result = verify_paths_notarized(root, sorted(paths), rebuild_index=rebuild_index)
    tc = TrustChainHelper(root, auto_init=False)
    result["trustchain_active"] = tc.has_trustchain()
    if not result.get("ok"):
        result["agent_message"] = result.get("rejection_prompt") or result.get("agent_prompt")
    return result


def register_enforcement_policy_hook() -> bool:
    """TrustChain policy: only ``apatch`` tool_id may sign mutating commits when enforcing."""
    global _APATCH_POLICY_REGISTERED
    if _APATCH_POLICY_REGISTERED:
        return True
    try:
        from trustchain.v2.policy_hooks import get_policy_registry

        allowed = {"apatch", "apatch_expert", "test_runner"}

        def _require_apatch_notarization(response, context):
            ctx = context or {}
            workspace = ctx.get("workspace")
            if workspace and not is_enforcement_enabled(workspace):
                return True
            src = ctx.get("source")
            if src != "apatch":
                return True
            tid = response.tool_id or ""
            # Governed session attest and other first-party apatch_* ledger writes.
            if tid in allowed or tid.startswith("apatch_"):
                return True
            return False

        reg = get_policy_registry()
        if not any(getattr(h, "__name__", "") == "_require_apatch_notarization" for h in reg._hooks):
            reg.register(_require_apatch_notarization)
        _APATCH_POLICY_REGISTERED = True
        return True
    except ImportError:
        return False


def ensure_enforcement_hooks(root: str) -> None:
    if is_enforcement_enabled(root):
        register_enforcement_policy_hook()


def assert_can_apply(root: str, *, no_trustchain: bool = False) -> Optional[str]:
    """Return error message if apply must be blocked."""
    if not is_enforcement_enabled(root):
        return None
    cfg = load_enforcement_config(root)
    if no_trustchain and cfg.get("require_trustchain_on_apply", True):
        return apply_blocked_message("no_trustchain")
    tc = TrustChainHelper(root, auto_init=False)
    if cfg.get("require_trustchain_on_apply", True) and not tc.has_trustchain():
        TrustChainHelper(root, auto_init=True)
    return None


def assert_notarization_committed(
    root: str,
    *,
    committed: bool,
    files_meta: Dict[str, Dict[str, Any]],
) -> Optional[str]:
    if not is_enforcement_enabled(root):
        return None
    cfg = load_enforcement_config(root)
    if not cfg.get("fail_apply_if_notarization_fails", True):
        return None
    if committed:
        return None
    paths = list(files_meta.keys())[:8]
    extra = len(files_meta) - len(paths)
    suffix = f" (+{extra} more)" if extra > 0 else ""
    return build_rejection_prompt(
        reason="notarization_failed",
        paths=paths,
        detail=f"TrustChain не записал Ed25519 block на диск. Откат выполнен{suffix}.",
    )


def verify_commit_produced_block(
    tc: TrustChainHelper,
    blocks_before: Optional[int] = None,
) -> bool:
    """Validate the last O(1) commit receipt."""
    if not tc.has_trustchain():
        return False
    cfg = load_enforcement_config(tc.workspace_root)
    if not cfg.get("require_ed25519_block_on_disk", True):
        return True
    receipt = tc.last_commit_evidence
    if receipt:
        return bool(
            receipt.get("persisted")
            and receipt.get("signature_valid")
            and receipt.get("record_valid")
            and receipt.get("head_valid")
        )
    if blocks_before is None:
        return False
    return tc.count_signed_blocks() > blocks_before
